# Imaging Masks
wall_hsv_mask :
  mask:
    - 119
    - 73
    - 192
fog_hsv_mask : # [101 147 184]
  mask:
    - 99
    - 226
    - 191
  offsets:
    - 10
    - 50
    - 10
waypoint_hsv_mask :
  mask:
    - 111
    - 10
    - 255
