items :
  - "orb of alteration"
  #- "orb of chance"
  - "orb of fusing"
  #- "orb of transmutation"
  #- "orb of scouring"
  #- "orb of horizons"
  #- "orb of augmentation"
  - "orb of regret"
  - "divine orb"
  - "exalted orb"
  - "chaos orb"
  #- "engineer’s orb"
  - "jeweller’s orb"
  #- "chromatic orb"
  - "beastiary orb"
  #- "blessed orb"
  - "vaal orb"
  #- "ancient orb"
  - "awakener’s orb"
  - "crusader’s exalted orb"
  - "eternal orb"
  - "hunter’s exalted orb"
  - "redeemer’s exalted orb"
  - "warlord’s exalted orb"
  - "regal orb"
  #- "glassblower’s bauble"
  #- "awakened sextant"
  #- "portal scroll"
  #- "armourer’s scrap"
  #- "blacksmith’s whetstone"
  - "silver coin"
  - "cartographer’s chisel"
  - "facetor’s lens"
  - "imbued catalyst"
  - "simple sextant"
  - "prime sextant"
  - "gemcutter’s prism"
  - "albino rhoa feather"
  - "mirror of kalandra"
  # T1 wild seeds
  - "wild ape seed"
  - "wild hatchling seed"
  - "wild hellion seed"
  - "wild thornwolf seed"
  - "wild ursaling seed"
  # T1 vivid
  - "vivid arachnid seed"
  - "vivid leech seed"
  - "vivid scorpion seed"
  - "vivid thornweaver seed"
  - "vivid weta seed"
  # T1 primal
  - "primal cleaveling seed"
  - "primal dustspitter seed"
  - "primal feasting horror seed"
  - "primal maw seed"
  - "primal rhoa seed"
  # Issues with ocr
  - "WILD THORNWOLE SEED"
  - "BELACKSMITH’S WHETSTONE"
  - "DrvtNe ORB"
  - "VivID WETA SEED"